// Compares a map's `meta.formatVersion` against the version this build expects.
// Returns a user-facing error message when they differ (older or newer), or null
// when the map is compatible. A missing/invalid version is treated as older.
export function formatVersionError(
  mapVersion: number | undefined,
  expected: number,
): string | null {
  const v = typeof mapVersion === "number" ? mapVersion : 0;
  if (v === expected) return null;
  const rel = v < expected ? "an older" : "a newer";
  return (
    `This map was generated by ${rel} version of SQLinsite ` +
    `(map format v${v}, this build expects v${expected}). ` +
    `Regenerate it with \`sqlinsite map\`.`
  );
}
